#!/bin/bash

# Java Project Creator
#
# A simple script to create a new Java program
#
# Author: Daniel Hammer
# Date: 2021-04-19
#
# Exit codes:
# 0 - Program success
# 1 - Insufficient usage
# 2 - Project name already exists


# Check args
if [ $# -lt 1 ]; then
    echo "usage: jvnew <project name>"
    exit 1
fi

# Get name of project
name=$1

# If the directory already exists, throw an error
if [ -d "$name" ]; then
    echo "Error: $name already exists"
    exit 2
fi

# Set up directory structure
mkdir -p $name/src/application
mkdir -p $name/bin

# Set up Main class
echo "
package application;

/**
* Driver Class
*/
public class Main {
    public static void main(String[] args) {
        System.out.println(\"Hello, world!\");
    }
}
" > $name/src/application/Main.java

# Set up README.md
echo "
# Title
" > $name/README.md

# Initialize Git repository
git init $name/


# End
echo "Created new Java project: $name"
exit 0
